### ISSUE TITLE
The compute engine completely stops when the application loses focus

### ISSUE THREAD

**Issue by aalex** [Xmodal/dynamiclight#49] opened 2020-06-16 20:41 UTC
After a while, the update rate drops to almost completely stop.

The current backend model that implements the minimum required to run generators in the backend. It runs a single thread for running generators separate from the GUI thread.

It still has some timing issues — it will become unstable when other applications are taking up a lot of CPU, and also when the app is not the "topmost" or "active" app on the operating system. Unfortunately when it does, it becomes unusable. The framerate crashes down from 30Hz to less than 1 update per 5 seconds. This might be a bug with QTimer, or this might just be a bad implementation. More investigation is required. A much more stable (but terribly energy and CPU-inefficient) solution would be busy waiting.

**Comment by simondemeule** [comment] 2020-07-01 20:08
Some progress was made on this — part of the instability was caused by the compute engine not actually running on its own thread due to the way its timer worked — it relied on the GUI thread's event loop to function. This is now fixed in branch fix-compute-engine-crashes-and-instability, but more work needs to be done, as the engine still stalls when losing focus, and there seems to be threading bugs still present.

**Comment by simondemeule** [comment] 2020-07-01 20:57
I'm currently discussing this issue and #88 [on a monome forum thread dedicated to audio programming](https://llllllll.co/t/lower-level-audio-programming/1259/85).

**Comment by aalex** [comment] 2020-07-02 16:17
As I mentioned, I suggest to avoid writing a multi-thread application, for now. It would be a lot easier. Premature optimization is the root of all evil. (See https://stackify.com/premature-optimization-evil/ )

If you want to continue to develop a multi-thread application anyhow, I've sent you a few links:

- Check dans MapMap 0.6, on avait une thread séparée pour l'OscReceiver. (maintenant, c'est du passé) https://github.com/mapmapteam/mapmap/blob/0.6/src/control/OscReceiver.cpp#L11 La thread était gérée à 100% à l'intérieur d'un objet. Pour communiquer avec le monde extérieur, on utilisait une messaging queue. 
- https://github.com/mapmapteam/mapmap/blob/0.6/src/control/OscInterface.cpp#L89 - C'est simplement le Command Design Pattern.

**Comment by simondemeule** [comment] 2020-07-06 22:17
Looks like this issue is specific to macOS, and is caused by a power management feature of the operating system — timer coalescing or "App Nap" as Apple calls it. I've confirmed that this is indeed the problem, as turning off that feature system-wide using `sudo sysctl -w kern.timer.coalescing_enabled=0` prevents the compute engine from stalling. [I found some information](https://github.com/msorvig/qt-and-app-nap) that addresses this specifically in the context of Qt timers (our exact problem!). It seems really straightforward but I'm having a bit of a hard time making it work — @aalex do you know how to make these magical `.mm` files work? Also related: [this stackoverflow thread](https://stackoverflow.com/questions/19577541/disabling-timer-coalescing-in-osx-for-a-given-process).

**Comment by simondemeule** [comment] 2020-07-07 01:04
[Another relevant thread](https://stackoverflow.com/questions/30686488/qapplication-is-lazy-or-making-other-threads-lazy-in-the-app).

**Closed** 2020-07-24 18:19 UTC
Labels: 0 points, C++, Ready, bug
